name: Gran Calavera
markdown: redcarpet
pygments: true
timezone: Europe/London
destination: gh-pages
source: jekyll
permalink: pretty
relative_permalinks: false
url: http://grancalavera.com
exclude: ['styles']
