name: grancalavera
markdown: redcarpet
pygments: true
timezone: Europe/London
exclude: [
  "node_modules",
  "bower_components",
  "sass",
  "*.sublime-*",
  "bower.json",
  "Gemfile*",
  "package.json",
  "README.md",
  "Gruntfile.js"
  ]
