name: grancalavera
markdown: redcarpet
pygments: true
timezone: Europe/London
destination: gh-pages
exclude: [
  "node_modules",
  "bower_components",
  "sass",
  "*.sublime-*",
  "bower.json",
  "Gemfile*",
  "package.json",
  "Gruntfile.js",
  "gh-pages"
  ]
